# Adjust the settings and rename to "config.yaml"
application_settings:
  port: 8080
  host: "0.0.0.0"
database_settings:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_settings:
  base_url: "127.0.0.1"
  sender_email: "onboarding@resend.dev"
  resend_api_key: "get from resend.com"
redis_settings:
  uri: "redis://127.0.0.1:6379"
super_user:
  username: testuser
  password: password123
