# Adjust the settings and rename to "config.yaml"
application_settings:
  port: 8080
  host: "127.0.0.1"
database_settings:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_settings:
  base_url: "127.0.0.1"
  sender_email: "onboarding@resend.dev"
  # Obtain From resend.com (free service)
  resend_api_key: "your api key"
redis_settings:
  uri: "redis://127.0.0.1:6379"
test_mode: true
